name: docker-build

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    name: auto build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
          repository: yobot/yobot
          tags: latest,slim
